import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "PROJECT NAME",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} h-screen bg-black flex justify-center  `}
      >
        {/* <div className=" border-2 border-green-600 rounded-3xl max-w-[90%] max-h-[90%] w-full h-full overflow-auto ">
          {" "} */}
        {children}
        {/* </div> */}
      </body>
    </html>
  );
}
