import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

//To add another font, import it into the component and set a variable and add it to the classname of the element as done here.

export const metadata: Metadata = {
  title: "Dr. Christopher Davis | Plastic Surgeon",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className=" ">
      {/* overscroll-y-none */}
      <body
        className={`${inter.className}  h-[100svh] sm:h-screen bg-bg flex justify-center select-none relative  grow   `}
      >
        {/* <div className=" border-2 border-green-600 rounded-3xl max-w-[90%] max-h-[90%] w-full h-full overflow-auto ">
          {" "} */}
        {children}
        {/* </div> */}
      </body>
    </html>
  );
}
